In [1]:
import tensorflow as tf
print('done')

C:\Users\Lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


done


In [3]:
a = tf.constant(100)

In [5]:
print(a)

tf.Tensor(100, shape=(), dtype=int32)


In [6]:
a = tf.constant([1,24,354,3225])

print(a)

tf.Tensor([   1   24  354 3225], shape=(4,), dtype=int32)


In [7]:
# 0d: scaler value
# 1d:- vector
# 2d:- matrix
# 3d:- tensors

In [8]:
a = tf.constant([[1,24],[354,3225]])

print(a)

tf.Tensor(
[[   1   24]
 [ 354 3225]], shape=(2, 2), dtype=int32)


In [10]:
a = tf.Variable(100)
print(a)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


In [11]:
a = tf.Variable([100,20])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,  20])>


In [13]:
print(a[0])

tf.Tensor(100, shape=(), dtype=int32)


In [14]:
a[0] = 2345

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
a[0].assign(2345)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2345,   20])>

In [16]:
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2345,   20])>


In [18]:
print(dir(a[0]))

['OVERLOADABLE_OPERATORS', '_USE_EQUALITY', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__bool__', '__class__', '__complex__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__iter__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__tf_tensor__', '__tf_tracing_type__', '__truediv__', '__weakref__', '__xor__', '_add_consumer

In [19]:
import numpy as np

In [20]:
a = np.array([12,3,324,1])
b = np.array([12,432,421,4])


x  = tf.constant(a)
y  = tf.constant(b)

In [21]:
print(x)

tf.Tensor([ 12   3 324   1], shape=(4,), dtype=int32)


In [22]:
print(y)

tf.Tensor([ 12 432 421   4], shape=(4,), dtype=int32)


In [23]:
print(x + y)

tf.Tensor([ 24 435 745   5], shape=(4,), dtype=int32)


In [24]:
print(x - y)

tf.Tensor([   0 -429  -97   -3], shape=(4,), dtype=int32)


In [25]:
print(x * y)

tf.Tensor([   144   1296 136404      4], shape=(4,), dtype=int32)


In [26]:
print(x / y)

tf.Tensor([1.         0.00694444 0.7695962  0.25      ], shape=(4,), dtype=float64)


In [27]:
print(x // y)

tf.Tensor([1 0 0 0], shape=(4,), dtype=int32)


In [28]:
print(x % y)

tf.Tensor([  0   3 324   1], shape=(4,), dtype=int32)


In [29]:
print(x ** y)

tf.Tensor([ -251658240 -1038867519           0           1], shape=(4,), dtype=int32)


In [30]:
tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 24, 435, 745,   5])>

In [31]:
tf.subtract(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   0, -429,  -97,   -3])>

In [32]:
tf.multiply(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   144,   1296, 136404,      4])>

In [33]:
tf.divide(x,y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1.        , 0.00694444, 0.7695962 , 0.25      ])>

In [34]:
a = np.random.randint(1,50,(3,3))
b = np.random.randint(1,50,(3,3))

x  = tf.constant(a)
y  = tf.constant(b)

In [36]:
print(x)

tf.Tensor(
[[ 7  6 23]
 [30 48 39]
 [23 45  1]], shape=(3, 3), dtype=int32)


In [37]:
print(y)

tf.Tensor(
[[49  1 26]
 [42 21 42]
 [34 35 13]], shape=(3, 3), dtype=int32)


In [38]:
print(x*y)

tf.Tensor(
[[ 343    6  598]
 [1260 1008 1638]
 [ 782 1575   13]], shape=(3, 3), dtype=int32)


In [39]:
49*7

343

In [40]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1377,  938,  733],
       [4812, 2403, 3303],
       [3051, 1003, 2501]])>

In [41]:
# tf.reduce_max
# tf.reduce_mean
# tf.reduce_min
# tf.reduce_prod
# tf.reduce_sum
# tf.reduce_all
# tf.reduce_any

In [42]:
a = tf.Variable([[1,2,34],[3,4,5]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2, 34],
       [ 3,  4,  5]])>


In [47]:
print(tf.reduce_max(a))
print(tf.reduce_mean(a))
print(tf.reduce_min(a))
print(tf.reduce_prod(a))
print(tf.reduce_sum(a))

tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4080, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)


In [48]:
# with axis
print(tf.reduce_max(a,axis = 1))
print(tf.reduce_mean(a,axis = 1))
print(tf.reduce_min(a,axis = 1))
print(tf.reduce_prod(a,axis = 1))
print(tf.reduce_sum(a,axis = 1))

tf.Tensor([34  5], shape=(2,), dtype=int32)
tf.Tensor([12  4], shape=(2,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([68 60], shape=(2,), dtype=int32)
tf.Tensor([37 12], shape=(2,), dtype=int32)


In [49]:
# with axis
print(tf.reduce_max(a,axis = 0))
print(tf.reduce_mean(a,axis = 0))
print(tf.reduce_min(a,axis = 0))
print(tf.reduce_prod(a,axis = 0))
print(tf.reduce_sum(a,axis = 0))

tf.Tensor([ 3  4 34], shape=(3,), dtype=int32)
tf.Tensor([ 2  3 19], shape=(3,), dtype=int32)
tf.Tensor([1 2 5], shape=(3,), dtype=int32)
tf.Tensor([  3   8 170], shape=(3,), dtype=int32)
tf.Tensor([ 4  6 39], shape=(3,), dtype=int32)


In [51]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2, 34],
       [ 3,  4,  5]])>


In [52]:
a = tf.Variable([[1,2,34],[3,4,5]],dtype = tf.float64)
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>


In [53]:
# with axis
print(tf.reduce_max(a,axis = 0))
print(tf.reduce_mean(a,axis = 0))
print(tf.reduce_min(a,axis = 0))
print(tf.reduce_prod(a,axis = 0))
print(tf.reduce_sum(a,axis = 0))

tf.Tensor([ 3.  4. 34.], shape=(3,), dtype=float64)
tf.Tensor([ 2.   3.  19.5], shape=(3,), dtype=float64)
tf.Tensor([1. 2. 5.], shape=(3,), dtype=float64)
tf.Tensor([  3.   8. 170.], shape=(3,), dtype=float64)
tf.Tensor([ 4.  6. 39.], shape=(3,), dtype=float64)


In [54]:
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [56]:
print(tf.reshape(a,(3,2)))

tf.Tensor(
[[ 1.  2.]
 [34.  3.]
 [ 4.  5.]], shape=(3, 2), dtype=float64)


In [59]:
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(2, 1, 3), dtype=float64, numpy=
array([[[ 1.,  2., 34.]],

       [[ 3.,  4.,  5.]]])>

In [60]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  2., 34.],
        [ 3.,  4.,  5.]]])>

In [63]:
a = tf.expand_dims(a,axis=0)

In [64]:
a

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  2., 34.],
        [ 3.,  4.,  5.]]])>

In [65]:
tf.squeeze(a)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [66]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2, 1), dtype=float64, numpy=
array([[[ 1.],
        [ 3.]],

       [[ 2.],
        [ 4.]],

       [[34.],
        [ 5.]]])>

In [69]:
a.shape

TensorShape([1, 2, 3])

In [70]:
# Broadcasting and Indexing

In [71]:
print(a)

tf.Tensor(
[[[ 1.  2. 34.]
  [ 3.  4.  5.]]], shape=(1, 2, 3), dtype=float64)


In [72]:
a[0]

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [73]:
a[-1]

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [74]:
a[0][0]

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  2., 34.])>

In [75]:
a[:,0]

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[ 1.,  2., 34.]])>

In [76]:
a[0,:]

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [77]:
a[1:0]

<tf.Tensor: shape=(0, 2, 3), dtype=float64, numpy=array([], shape=(0, 2, 3), dtype=float64)>

In [78]:
print(a)

tf.Tensor(
[[[ 1.  2. 34.]
  [ 3.  4.  5.]]], shape=(1, 2, 3), dtype=float64)


In [80]:
a = tf.squeeze(a)

In [81]:
a

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [82]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[ 1.,  3.],
       [ 2.,  4.],
       [34.,  5.]])>

In [84]:
a*10

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 10.,  20., 340.],
       [ 30.,  40.,  50.]])>

In [85]:
a+10

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[11., 12., 44.],
       [13., 14., 15.]])>

In [86]:
a+a

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 2.,  4., 68.],
       [ 6.,  8., 10.]])>

In [87]:
a

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2., 34.],
       [ 3.,  4.,  5.]])>

In [95]:
# Casting & masking

In [90]:
print(a)

tf.Tensor(
[[ 1.  2. 34.]
 [ 3.  4.  5.]], shape=(2, 3), dtype=float64)


In [91]:
a==1

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False, False, False]])>

In [93]:
print(a[a==1])

tf.Tensor([1.], shape=(1,), dtype=float64)


In [94]:
# data type from one to another type casting

In [96]:
a = tf.Variable([1.0,3.0,5.0,6.0,8.0], dtype = tf.float16)
print(a)

<tf.Variable 'Variable:0' shape=(5,) dtype=float16, numpy=array([1., 3., 5., 6., 8.], dtype=float16)>


In [98]:
print(tf.cast(a,dtype=tf.int32))

tf.Tensor([1 3 5 6 8], shape=(5,), dtype=int32)


In [99]:
# One Hot Encoding

In [102]:
text_data = ['Delhi','Mumbai','faridabad']

indexes = [0,1,2]


tf.one_hot(indexes,depth= 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
tf.sort
tf.argmax
tf.argsort
tf.linspace